name: Build DooN Wizard
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        # استخدام النسخة الرسمية مع تحديد المسارات يدوياً لحل "Repository not found"
        uses: theos/setup-theos-action@v1
        with:
          theos-src: https://github.com/theos/theos.git
          theos-sdks: https://github.com/theos/sdks.git

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1
        env:
          THEOS: /opt/theos

      - name: Upload Result
        # v4 لحل مشكلة deprecation اللي في صورة 1148
        uses: actions/upload-artifact@v4
        with:
          name: DooN_Wizard_Final
          path: .theos/obj/debug/*.dylib