name: Build DooN Wizard
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos Manually
        run: |
          sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip -d /opt/theos/sdks
          echo "THEOS=/opt/theos" >> $GITHUB_ENV
        # دي طريقة يدوية بتنزل الأدوات غصب عن أي خطأ في الروابط التلقائية

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1
        env:
          THEOS: /opt/theos

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: DooN_Wizard_Final
          path: .theos/obj/debug/*.dylib