name: Build DooN Wizard
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        # استخدام النسخة الرسمية والمستقرة من theos-action
        uses: theos/setup-theos-action@v1.0.3

      - name: Build Tweak
        run: |
          make package
        env:
          THEOS: /opt/theos

      - name: Upload Result
        # تحديث إلى v4 لحل خطأ "deprecated version" (الصورة IMG_1148)
        uses: actions/upload-artifact@v4
        with:
          name: DooN_Wizard_Final
          path: .theos/obj/debug/*.dylib