name: Build DooN Wizard
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos Clean
        run: |
          # تنظيف وبناء المسار بشكل احترافي
          rm -rf $HOME/theos
          git clone --depth=1 https://github.com/theos/theos.git $HOME/theos
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos/sdks
          # سطر السحر: تعريف المسار في بيئة النظام بشكل دائم
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          # استخدام المسار المعرف مباشرة
          make package FINALPACKAGE=1 THEOS=$HOME/theos
        # ضفنا THEOS=$HOME/theos هنا كمان عشان نضمن إن الـ Makefile يشوفه (حل صورة 1157)

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: DooN_Wizard_Final
          path: .theos/obj/debug/*.dylib